"""Create tables

Revision ID: a71490af6d65
Revises: 
Create Date: 2024-10-26 12:58:25.218117

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a71490af6d65'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('c_id', sa.Integer(), nullable=False),
    sa.Column('c_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('salt', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('c_id'),
    sa.UniqueConstraint('c_name')
    )
    op.create_table('restaurants',
    sa.Column('r_id', sa.Integer(), nullable=False),
    sa.Column('r_name', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('salt', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('r_id'),
    sa.UniqueConstraint('r_name')
    )
    op.create_table('evaluations',
    sa.Column('e_id', sa.Integer(), nullable=False),
    sa.Column('c_id', sa.Integer(), nullable=False),
    sa.Column('e_day', sa.DateTime(), nullable=True),
    sa.Column('evaluation', sa.Boolean(), nullable=False),
    sa.Column('total_quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['c_id'], ['customers.c_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('e_id')
    )
    op.create_table('foods',
    sa.Column('f_id', sa.Integer(), nullable=False),
    sa.Column('r_id', sa.Integer(), nullable=False),
    sa.Column('f_name', sa.String(length=255), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('tag', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['r_id'], ['restaurants.r_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('f_id'),
    sa.UniqueConstraint('f_name')
    )
    op.create_table('orders',
    sa.Column('o_id', sa.Integer(), nullable=False),
    sa.Column('c_id', sa.Integer(), nullable=False),
    sa.Column('r_id', sa.Integer(), nullable=False),
    sa.Column('o_datetime', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['c_id'], ['customers.c_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['r_id'], ['restaurants.r_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('o_id')
    )
    op.create_table('food_alcohol',
    sa.Column('f_id', sa.Integer(), nullable=False),
    sa.Column('degree', sa.Float(), nullable=False),
    sa.Column('f_quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['f_id'], ['foods.f_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('f_id')
    )
    op.create_table('order_items',
    sa.Column('oi_id', sa.Integer(), nullable=False),
    sa.Column('o_id', sa.Integer(), nullable=False),
    sa.Column('f_id', sa.Integer(), nullable=False),
    sa.Column('o_quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['f_id'], ['foods.f_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['o_id'], ['orders.o_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('oi_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_items')
    op.drop_table('food_alcohol')
    op.drop_table('orders')
    op.drop_table('foods')
    op.drop_table('evaluations')
    op.drop_table('restaurants')
    op.drop_table('customers')
    # ### end Alembic commands ###
